SELECT b."i1_anio" AS ANIO  , b."i2_fecnotif" AS FECHANOTIFICACION , b."i3_institucion" AS institucion , b."i4_unidadoperativa" AS  UnidadOperativa, b."i4_unicodigo" AS Unicodigo, b."i5_zona" AS ZONA, b."i6_cod_distrito" AS codigo_distrito, b."i7_cod_provincia" AS Provincia_des, b."i8_cod_canton" AS Canton_des, b."i9_cod_parroquia" AS Parroquia_des, 
b."i10_fecatencion" AS FECHAINICIOATENCION, b."i11_nacionalidad" AS NACIONALIDAD, b."i12_cod_provdomic" Codigo_Provincia, b."i13_cod_cantondomic" AS Canton_id, b."i14_cod_parroqdomic" AS Parroquia_id, b."i15_sexo" AS SEXO, b."i16_edad" AS EDAD, b."i16_edadtipo" AS TIPOEDAD, b."i16_edadrango" AS GRUPOEDAD, b."i17_autoidentificacion" AS AUTOIDENTIFICACION, b."i18_iniciodesintomas" AS FECHAINICIOSINTOMA, b."i19_se" AS SEMANA, b."i20_lugardeatencion" AS lugar_atencion, b."i21_condicionfinal" AS condicion_final, b."i22_fecfallec" AS FECHAFALLECIMIENTO, 
b."i23_clasificacionfinaldelcaso" AS clasificacion_final_caso,
b."i24_diagnosticofinal" AS DIAGNOSTICOFINALCIE, b."i25_evento", b."i26_confirmadopor" AS CONFIRMADOPOR
FROM HCUE_VIGILANCIA.MIGRAR_VIEPI_INDIVIDUAL b;


/*Consulta Epindividual*/
SELECT e.ID AS EPINDIVIDUAL_ID,e.ANIO,e.DIAGNOSTICOATENCION_ID ,e.FECHANOTIFICACION ,ov.DESCRIPCION AS INSTITUCION,ov3.DESCRIPCION AS TIPO_INSTITUCION,xe.NOMBREOFICIAL AS UnidadOperativa,xe.ID AS Unicodigo,z.DESCRIPCION AS ZONA,dy.CODIGO AS codigo_distrito ,
p.ID AS PARROQUIA_IDENTIDAD,p.DESCRIPCION AS PARROQUIA_ENTIDAD,c.ID AS CANTON_IDENTIDAD,c.DESCRIPCION AS CANTON_ENTIDAD,p2.ID AS PROVINCIA_IDENTIDAD,p2.DESCRIPCION AS PROVINCIA_ENTIDAD,e.DIRECCIONINFECCION,
au.FECHAINICIOATENCION,pp.NUMEROHISTORIACLINICA ,pni.NOMBRECOMPLETO  ,e.SEXO_ID,(SELECT c.DESCRIPCION  FROM HCUE_CATALOGOS.DETALLECATALOGO c WHERE c.ID = e.SEXO_ID  )SEXO ,pni.FECHANACIMIENTO,(SELECT vk.DESCRIPCION FROM HCUE_CATALOGOS.DETALLECATALOGO vk WHERE vk.ID = pni.CTNIVELEDUCACION_ID)AS N_EDUCATIVO,(SELECT vk.DESCRIPCION FROM HCUE_CATALOGOS.DETALLECATALOGO vk WHERE vk.ID = pni.CTESTADOCIVIL_ID)AS ESTADO_CIVIL,
e.EDAD,(SELECT v6.DESCRIPCION FROM HCUE_CATALOGOS.DETALLECATALOGO v6 WHERE v6.ID= e.TIPOEDAD_ID)AS TIPO_EDAD, e.TIPOEDAD_ID,(SELECT v9.DESCRIPCION FROM HCUE_CATALOGOS.DETALLECATALOGO v9 WHERE v9.ID= e.GRUPOEDAD_ID)AS GRUPO_EDAD ,e.GRUPOEDAD_ID,
(SELECT n7.DESCRIPCION FROM HCUE_CATALOGOS.DETALLECATALOGO n7 WHERE n7.ID= e.AUTOIDENTIFICACION_ID)AS AUTOINDETIFICACION,e.AUTOIDENTIFICACION_ID ,p3.ID AS PAIS_ID,p3.ID AS NACIONALIDAD_ID,p3.DESCRIPCION AS PAIS,p3.NACIONALIDAD,pacv.ID AS PROVINCIA_ID,pacv.DESCRIPCION AS PROVINCIA_PACIENTE ,
pac.ID AS PARROQUIA_ID, pac.DESCRIPCION AS PARROQUIA_PACIENTE,cac.ID AS CANTON_ID, cac.DESCRIPCION AS CANTON_PACIENTE, 
e.FECHAINICIOSINTOMA,e.SEMANAEPI_ID ,s.SEMANA,e.REQUIEREMUESTRA,e.CTRESULTADOMUESTRA_ID ,
(SELECT nb.DESCRIPCION FROM HCUE_CATALOGOS.DETALLECATALOGO nb WHERE nb.ID = e.CTRESULTADOMUESTRA_ID)AS CTRESULTADOMUESTRA, e.REALIZOINVESTIGACION, e.FECHAINVESTIGACION, e.CONTACTOSINTOMATICO 
,e.SEMANAEPICREACION_ID ,sl.SEMANA AS SEMANAEPICREACION,e.FECHAINICIOSINTOMAEPI ,e.CTLUGARATENCION_ID ,
(SELECT d3.DESCRIPCION  FROM HCUE_CATALOGOS.DETALLECATALOGO d3 WHERE d3.ID= e.CTLUGARATENCION_ID)lugar_atencion,e.CTCONDICIONFINAL_ID ,
(SELECT d.DESCRIPCION  FROM HCUE_CATALOGOS.DETALLECATALOGO d  WHERE d.ID= e.CTCONDICIONFINAL_ID) condicion_final,
e.FECHAFALLECIMIENTO,e.CTCLASIFICACIONFINAL_ID ,(SELECT d2.DESCRIPCION  FROM HCUE_CATALOGOS.DETALLECATALOGO d2 WHERE d2.ID= e.CTCLASIFICACIONFINAL_ID)clasificacion_final_caso,
e.DIAGNOSTICOFINALCIE_ID ,c2.NOMBRE AS DIAGNOSTICOFINALCIE,c2.CODIGO AS CODIGO_CIE,e.CTCONFIRMADOPOR_ID ,
(SELECT d4.DESCRIPCION FROM HCUE_CATALOGOS.DETALLECATALOGO d4 WHERE d4.ID= e.CTCONFIRMADOPOR_ID)CONFIRMADOPOR,
e.FECHADEFINIOCASO ,e.FECHACIERRECASO,e.FECHACREACION ,E.FECHAMODIFICACION , e.ESTADO, e.ACTIVO ,e.EXTERNO, e.FICHAINVESTIGACION,
e.EPRESULTADOCASO_ID ,e2.OBSERVACION AS EPRESULTADOCASO,e.CUMPLEDEFINICION_ID ,
(SELECT ym.DESCRIPCION FROM HCUE_CATALOGOS.DETALLECATALOGO ym WHERE ym.ID = e.CUMPLEDEFINICION_ID)AS CUMPLEDEFINICION,e.MOTIVOCUMPLEDEFINICION, e.OBSERVACIONFINALCIE,e.GESTACIONACTUAL_ID , e.SEMANAGESTACIONACTUAL ,
e.FUMATENCION, e.USUARIOCREACION_ID, e.USUARIOMODIFICACION_ID, e.USUARIODEFINIOCASO_ID 
FROM  HCUE_VIGILANCIA.EPINDIVIDUAL e
LEFT OUTER JOIN HCUE_AMED.DIAGNOSTICOATENCION dl ON dl.ID = e.DIAGNOSTICOATENCION_ID 
LEFT OUTER  JOIN HCUE_AMED.ATENCIONMEDICA au ON au.ID = dl.ATENCIONMEDICA_ID 
LEFT  OUTER JOIN HCUE_AMED.PACIENTE pp ON pp.ID  = au.PACIENTE_ID 
LEFT  OUTER JOIN HCUE_SISTEMA.PERSONA pni ON pni.ID = pp.PERSONA_ID 
LEFT OUTER  JOIN HCUE_SISTEMA.ENTIDAD xe ON xe.ID  = au.ENTIDAD_ID 
LEFT OUTER JOIN HCUE_CATALOGOS.CIRCUITO ci ON ci.ID = xe.CIRCUITO_ID 
LEFT OUTER JOIN HCUE_CATALOGOS.DISTRITO dy ON dy.ID = ci.DISTRITO_ID 
LEFT OUTER JOIN HCUE_CATALOGOS.ZONA z ON z.ID = dy.ZONA_ID 
LEFT OUTER JOIN HCUE_CATALOGOS.ORGANICO ov ON ov.ID  = xe.ORGANICO_ID
LEFT OUTER  JOIN HCUE_CATALOGOS.ORGANICO ov2 ON ov2.id = ov.ORGANICO_ID 
LEFT OUTER JOIN  HCUE_CATALOGOS.ORGANICO ov3 ON ov3.ID =ov2.ORGANICO_ID
LEFT OUTER JOIN HCUE_CATALOGOS.PARROQUIA p  ON p.ID = xe.PARROQUIA_ID  
LEFT OUTER JOIN HCUE_CATALOGOS.CANTON c ON p.CANTON_ID = c.ID 
LEFT  OUTER JOIN HCUE_CATALOGOS.PROVINCIA p2 ON c.PROVINCIA_ID = p2.ID 
LEFT OUTER  JOIN HCUE_CATALOGOS.PARROQUIA pac ON pac.ID = e.PARROQUIA_ID 
LEFT OUTER  JOIN HCUE_CATALOGOS.CANTON cac ON pac.CANTON_ID = cac.ID 
LEFT  OUTER JOIN HCUE_CATALOGOS.PROVINCIA pacv ON cac.PROVINCIA_ID = pacv.ID 
LEFT OUTER   JOIN  HCUE_CATALOGOS.PAIS p3 ON p3.ID = e.PAIS_ID
LEFT OUTER JOIN HCUE_CATALOGOS.CIE c2 ON c2.ID = e.DIAGNOSTICOFINALCIE_ID 
LEFT OUTER JOIN HCUE_VIGILANCIA.SEMANAEPI s ON s.ID = e.SEMANAEPI_ID
LEFT OUTER JOIN HCUE_VIGILANCIA.SEMANAEPI sl ON sl.ID = e.SEMANAEPICREACION_ID 
LEFT  OUTER JOIN HCUE_VIGILANCIA.EPRESULTADOCASO e2 ON e2.ID = e.EPRESULTADOCASO_ID 
;



/*Consulta Epi_muestra*/
SELECT pp.NUMEROHISTORIACLINICA ,pni.NOMBRECOMPLETO  ,e.SEXO_ID,(SELECT c.DESCRIPCION  FROM HCUE_CATALOGOS.DETALLECATALOGO c WHERE c.ID = e.SEXO_ID  )SEXO ,pni.FECHANACIMIENTO,(SELECT vk.DESCRIPCION FROM HCUE_CATALOGOS.DETALLECATALOGO vk WHERE vk.ID = pni.CTNIVELEDUCACION_ID)AS N_EDUCATIVO,(SELECT vk.DESCRIPCION FROM HCUE_CATALOGOS.DETALLECATALOGO vk WHERE vk.ID = pni.CTESTADOCIVIL_ID)AS ESTADO_CIVIL,
e.EDAD,(SELECT v6.DESCRIPCION FROM HCUE_CATALOGOS.DETALLECATALOGO v6 WHERE v6.ID= e.TIPOEDAD_ID)AS TIPO_EDAD, e.TIPOEDAD_ID,(SELECT v9.DESCRIPCION FROM HCUE_CATALOGOS.DETALLECATALOGO v9 WHERE v9.ID= e.GRUPOEDAD_ID)AS GRUPO_EDAD ,e.GRUPOEDAD_ID,
(SELECT n7.DESCRIPCION FROM HCUE_CATALOGOS.DETALLECATALOGO n7 WHERE n7.ID= e.AUTOIDENTIFICACION_ID)AS AUTOINDETIFICACION,e.AUTOIDENTIFICACION_ID ,p3.ID AS PAIS_ID,p3.ID AS NACIONALIDAD_ID,p3.DESCRIPCION AS PAIS,p3.NACIONALIDAD,pacv.ID AS PROVINCIA_ID,pacv.DESCRIPCION AS PROVINCIA_PACIENTE ,
pac.ID AS PARROQUIA_ID, pac.DESCRIPCION AS PARROQUIA_PACIENTE,cac.ID AS CANTON_ID, cac.DESCRIPCION AS CANTON_PACIENTE,fv.FECHAINICIOVIAJE,fv.FECHAFINALVIAJE,fv.LUGARVIAJE ,fv.ANTECEDENTEVIAJE,e.ID AS EPINDIVIDUAL_ID,emp.NOMBRE AS NOMBRE_MUESTRA,det.DESCRIPCION AS TIPO_MUESTRA,emp.FECHAENVIO, emp.FECHATOMA,emp.ESTADO AS ESTADO_MUESTRA,det2.DESCRIPCION AS RESULTADO_MUESTRA,emr.MUESTRAADECUADA ,emr.FECHARECEPCION,emr.FECHAPROCESAMIENTO ,emr.FECHAENTREGARESULTADOS,
(SELECT fx.DESCRIPCION FROM HCUE_CATALOGOS.DETALLECATALOGO fx WHERE fx.ID = fv.CTSERVICIO_ID)AS SERVICIO,emr.OBSERVACION,
xe.NOMBREOFICIAL AS ENTIDAD_PROCESOMUESTRA ,xe.ID AS Unicodigo,p.ID AS PARROQUIA_IDENTIDAD,p.DESCRIPCION AS PARROQUIA_ENTIDAD,c.ID AS CANTON_IDENTIDAD,c.DESCRIPCION AS CANTON_ENTIDAD,p2.ID AS PROVINCIA_IDENTIDAD,p2.DESCRIPCION AS PROVINCIA_ENTIDAD
FROM HCUE_VIGILANCIA.EPINDIVIDUAL e
LEFT OUTER JOIN HCUE_AMED.DIAGNOSTICOATENCION dl ON dl.ID = e.DIAGNOSTICOATENCION_ID 
LEFT OUTER  JOIN HCUE_AMED.ATENCIONMEDICA au ON au.ID = dl.ATENCIONMEDICA_ID 
LEFT  OUTER JOIN HCUE_AMED.PACIENTE pp ON pp.ID  = au.PACIENTE_ID 
LEFT  OUTER JOIN HCUE_SISTEMA.PERSONA pni ON pni.ID = pp.PERSONA_ID 
LEFT OUTER JOIN HCUE_VIGILANCIA.FICHAINVESTIGACION fv ON fv.EPINDIVIDUAL_ID  = e.ID
LEFT  OUTER  JOIN HCUE_VIGILANCIA.EPIMUESTRA emp ON emp.EPINDIVIDUAL_ID = e.ID 
LEFT  OUTER JOIN HCUE_CATALOGOS.DETALLECATALOGO det ON det.ID = emp.CTDETALLECATALOGO_ID 
LEFT OUTER JOIN  HCUE_VIGILANCIA.EPRESULTADOMUESTRA emr ON emr.EPIMUESTRA_ID = emp.ID 
LEFT  OUTER JOIN HCUE_CATALOGOS.DETALLECATALOGO det2 ON det2.ID = emr.CTRESULTADOMUESTRA_ID 
LEFT OUTER  JOIN HCUE_CATALOGOS.PARROQUIA pac ON pac.ID = e.PARROQUIA_ID 
LEFT OUTER  JOIN HCUE_CATALOGOS.CANTON cac ON pac.CANTON_ID = cac.ID 
LEFT  OUTER JOIN HCUE_CATALOGOS.PROVINCIA pacv ON cac.PROVINCIA_ID = pacv.ID 
LEFT OUTER   JOIN  HCUE_CATALOGOS.PAIS p3 ON p3.ID = e.PAIS_ID
LEFT OUTER  JOIN HCUE_SISTEMA.ENTIDAD xe ON xe.ID  = emr.CTRESULTADOMUESTRA_ID 
LEFT OUTER JOIN HCUE_CATALOGOS.PARROQUIA p  ON p.ID = xe.PARROQUIA_ID  
LEFT OUTER JOIN HCUE_CATALOGOS.CANTON c ON p.CANTON_ID = c.ID 
LEFT  OUTER JOIN HCUE_CATALOGOS.PROVINCIA p2 ON c.PROVINCIA_ID = p2.ID 
;

/*Consulta Epindividual + epi muestra y ficha de investigacion */
SELECT*FROM ( SELECT
          DISTINCT(EPI.ID)                     AS EPINDIVIDUAL_ID,
          TO_CHAR(FI.ID)                                AS FICHA_INVESTIGACION_ID,                             
          TO_CHAR(AMED.FECHACREACION, 'yyyy')             AS AÑO,
          TO_CHAR(AMED.FECHACREACION, 'mm')               AS MES,
          TO_CHAR(AMED.FECHACREACION, 'yyyy-mm-dd')       AS FECHA_ATENCION,
          CASE 
          WHEN ORG2.DESCRIPCION IS NULL THEN 'MSP'
          ELSE ORG2.DESCRIPCION 
          END                                AS INSTITUCION,
          TO_CHAR(ORG2.ID ) 							 AS INSTITUCION_ID,
          ENTIDAD.NOMBREOFICIAL              AS ESTABLECIMIENTO,
          TO_CHAR(ENTIDAD.ID )               AS UNICODIGO,
          TO_CHAR(ZONAENT.DESCRIPCION)                 AS ZONA,
          TO_CHAR(ZONAENT.ID)                       AS ZONAENT_ID,
          TO_CHAR(ZONAENT.CODIGO)                     AS ZONA_CODIGO,
          TO_CHAR(DISTRITOENT.CODIGO)                 AS CODIGO_DISTRITO,
          TO_CHAR(DISTRITOENT.ID)                      AS DISTRITOENT_ID,
          TO_CHAR( DISTRITOENT.DISTRIBUCION )          AS DISTRITO,
          TO_CHAR(PROVINCIAENT.CODPROVINCIA )  AS CODIGO_PROVINCIA,
          TO_CHAR(PROVINCIAENT.DESCRIPCION )           AS PROVINCIA,
          TO_CHAR(CANTONENT.CODCANTON )                AS CODIGO_CANTON,
          TO_CHAR(CANTONENT.DESCRIPCION)              AS CANTON,
          TO_CHAR(PARROQUIAENT.CODPARROQUIA )          AS CODIGO_PARROQUIA,
          TO_CHAR(PARROQUIAENT.DESCRIPCION)           AS PARROQUIA,
          TO_CHAR(AREA.DESCRIPCION)                   AS AREA_SECTOR,
          TO_CHAR( EPI.FECHAINICIOSINTOMA,'yyyy-mm-dd'  )      AS FECHA_INICIO_SINTOMA,
          TO_CHAR(EPI.FECHANOTIFICACION,'yyyy-mm-dd' )              AS FECHA_NOTIFICACION,
          TO_CHAR(SE.SEMANA)                          AS SEMANA_EPIDEMIOLOGICA1,
          TO_CHAR(SE.ID)                              AS SEMANAEPI_ID,
          TO_CHAR(SE.ANIO)							 AS SEMANAEPI_ANIO,
          TO_CHAR(PERSONACREACION.NOMBRECOMPLETO)     AS NOMBRE_NOTIFICA,
          TO_CHAR(PER.NOMBRECOMPLETO )                 AS NOMBRE_PACIENTE,
          TO_CHAR(CTTIPO.DESCRIPCION)                 AS TIPO_IDENTIFICACION,
          TO_CHAR(PER.NUMEROIDENTIFICACION)           AS NUMERO_IDENTIFICACION,
          TO_CHAR(PAC.NUMEROHISTORIACLINICA)          AS NUMERO_HISTORIA_CLINICA,
          TO_CHAR(PAIS.NACIONALIDAD)                  AS NACIONALIDAD,
          TO_CHAR(ETNIA.DESCRIPCION)                  AS AUTOIDENTIFICACION_ETNICA,
          TO_CHAR(NACIONALIDADETNICA.DESCRIPCION)     AS NACIONALIDAD_ETNICA,
          TO_CHAR(SEX.DESCRIPCION)                    AS SEXO,
          CASE 
          WHEN EPI.SEMANAGESTACIONACTUAL > 0  THEN    'SI'   
          ELSE '-'  
          END AS EMBARAZADA,
          TO_CHAR(EPI.SEMANAGESTACIONACTUAL)          AS SEMANA_GESTACION,
          TO_CHAR(PAIS.CODIGO)                        AS CODIGO_PAIS,
          TO_CHAR(PAIS.DESCRIPCION)                   AS PAIS,
          TO_CHAR(CIVIL.DESCRIPCION)                  AS ESTADO_CIVIL,
          TO_CHAR(PER.FECHANACIMIENTO, 'yyyy-mm-dd' )                AS FECHA_NACIMIENTO,
          EPI.EDAD                          AS EDAD,
          (SELECT v6.DESCRIPCION FROM HCUE_CATALOGOS.DETALLECATALOGO v6 WHERE v6.ID= EPI.TIPOEDAD_ID)AS TIPO_EDAD,
          (SELECT v9.DESCRIPCION FROM HCUE_CATALOGOS.DETALLECATALOGO v9 WHERE v9.ID= EPI.GRUPOEDAD_ID)AS GRUPO_EDAD,
          TO_CHAR(EDUCACION.DESCRIPCION)              AS NIVEL_EDUCACION,
          TO_CHAR(PROFESION.DESCRIPCION)              AS OCUPACION,
          TO_CHAR(PACPROVINCIA.CODPROVINCIA ) AS CODIGO_PROVINCIA_RESIDENCIA,
          TO_CHAR(PACPROVINCIA.DESCRIPCION)           AS PROVINCIA_RESIDENCIA,
          TO_CHAR(PACCANTON.CODCANTON )                AS CODIGO_CANTON_RESIDENCIA,
          TO_CHAR(PACCANTON.DESCRIPCION)              AS CANTON_RESIDENCIA,
          TO_CHAR(PACPARROQUIA.CODPARROQUIA)          AS CODIGO_PARROQUIA_RESIDENCIA,
          TO_CHAR(PACPARROQUIA.DESCRIPCION)           AS PARROQUIA_RESIDENCIA,
          TO_CHAR(PAC.TELEFONO)                       AS TELEFONO,
          TO_CHAR(PAC.ID)                             AS PACIENTE_ID,
          TO_CHAR(PAC.BARRIO)                       AS BARRIO,
          TO_CHAR(PAC.CALLEPRINCIPAL)               AS CALLEPRINCIPAL,
          TO_CHAR(PAC.CALLESECUNDARIA)              AS CALLESECUNDARIA,
          TO_CHAR(PAC.NUMERORESIDENCIA)             AS NUMERORESIDENCIA,
          TO_CHAR(CTGS.DESCRIPCION)                   AS GRUPOSANGUINEO,
          TO_CHAR(INFECCIONPAIS.CODIGO)               AS CODIGO_PAIS_INFECCION,
          TO_CHAR(INFECCIONPAIS.DESCRIPCION)          AS PAIS_INFECCION,
          TO_CHAR(INFECPRO.CODPROVINCIA)              AS CODIGO_PROVINCIA_INFECCION,
          TO_CHAR(INFECPRO.DESCRIPCION)               AS PROVINCIA_INFECCION,
          TO_CHAR(INFECCIONCANTON.CODCANTON)          AS CODIGO_CANTON_INFECCION,
          TO_CHAR(INFECCIONCANTON.DESCRIPCION)        AS CANTON_INFECCION,
          TO_CHAR(INFECPARR.CODPARROQUIA)             AS CODIGO_PARROQUIA_INFECCION,
          TO_CHAR(INFECPARR.DESCRIPCION)              AS PARROQUIA_INFECCION,
          TO_CHAR(EPI.DIRECCIONINFECCION)             AS LUGAR_PROBABLE_INFECCION,
          TO_CHAR(SECREACION.SEMANA)                  AS SEMANA_EPIDEMIOLOGICA2,
          TO_CHAR(CIE.CODIGO)                         AS CODIGOCIE1O,
          TO_CHAR(CIE.NOMBRE)                         AS DIAGNOSTICO_INICIAL,
          TO_CHAR(CIE.CODIGO)                         AS CODIGO_DIAGNOSTICO_INICIAL,
          TO_CHAR(CIE.NOTIFICACIONOBLIGATORIA)        AS NOTIFICACIONOBLIGATORIA,
          TO_CHAR(DIA.CTCONDICIONDIAGNOSTICO_ID)      AS CONDICION,
         (SELECT d.DESCRIPCION  FROM HCUE_CATALOGOS.DETALLECATALOGO d  WHERE d.ID= EPI.CTCONDICIONFINAL_ID) CONDICION_FINAL,
          TO_CHAR(DIA.CTCRONOLOGIADIAGNOSTICO_ID)     AS CRONOLOGIA,
          TO_CHAR(DPE.EXPUESTO)						 AS CONTACTOS_EXPUESTOS,
          TO_CHAR(DPE.EXPUESTOALTORIESGO) 			 AS CONTACTOS_ALTORIESGO,
          TO_CHAR(FI.NUMCASOSGENERAL)                AS NUMCASOSGENERAL,
          TO_CHAR(FI.LUGARVIAJE)                      AS LUGAR_VIAJE,
          TO_CHAR( FI.FECHAINICIOVIAJE,'yyyy-mm-dd' )      AS FECHA_INICIOVIAJE,
          TO_CHAR(FI.FECHAFINALVIAJE, 'yyyy-mm-dd')                  AS FECHA_FINAL_VIAJE,
          TO_CHAR(FI.ANTECEDENTEVIAJE) AS                ANTECEDENTEVIAJE,  
          TO_CHAR(PAC.NOMBRECONTACTO)                 AS NOMBRE_REPRESENTANTE,
          TO_CHAR(PAC.TELEFONOCONTACTO)               AS TELEFONOCONTACTO,
          TO_CHAR(PAC.DIRECCIONCONTACTO)              AS DIRECCIONCONTACTO,
          TO_CHAR(CTDIS.DESCRIPCION)                  AS DISCAPACIDAD,
          TO_CHAR(PUEBLO.DESCRIPCION)				 AS PUEBLO,
          CASE
          WHEN EPI.REQUIEREMUESTRA=0 THEN 'NO'
          ELSE 'SI'               
          END                                AS LABORATORIO,
          -----------------------------------------------------------------------------
          TO_CHAR(RESULTADO.DESCRIPCION)              AS RESULTADO,
          TO_CHAR(FI.DETALLECOMORBILIDAD)             AS COMORBILIDAD,
          TO_CHAR(FI.PRESENCIACOMORBILIDAD)           AS PRESENCIACOMORBILIDAD,
          TO_CHAR(AMDT.MODO_TRANSMISION)				 AS MODO_TRANSMISION,
          TO_CHAR(AFR.FACTOR_RIESGO)                  AS FACTOR_RIESGO,
          TO_CHAR(SYS.SIGNOS_SINTOMAS)               AS SIGNOS_SINTOMAS,
          --DETCATANT.DESCRIPCION  AS FACTOR_RIESGOS,
          -----------------------------------------------------------------------------
          TO_CHAR(FI.HOSPITALIZADO)                   AS HOSPITALIZADO,
          TO_CHAR(SERVICIO.DESCRIPCION)               AS SERVICIO,
          TO_CHAR(CONDICIONEGRESO.DESCRIPCION)        AS CONDICION_EGRESO,
          TO_CHAR(CLASIFICACIONCASO.DESCRIPCION)      AS CLASIFICACION_CASO,
          TO_CHAR(FI.CTCLASIFICACIONCASO_ID)          AS CTCLASIFICACIONCASO_ID,
          TO_CHAR(CLASIFICACIONFINAL.DESCRIPCION)     AS CLASIFICACION_FINAL_CASO,
          TO_CHAR(LUGARATENCION.DESCRIPCION)          AS LUGAR_ATENCION,
          TO_CHAR(EPI.FECHAFALLECIMIENTO,'yyyy-mm-dd' )              AS FECHA_FALLECIMIENTO,
          TO_CHAR(CONFIRMADOPOR.DESCRIPCION)          AS CONFIRMADO_POR,
          TO_CHAR(CIEFINAL.CODIGO)                    AS CODIGO_DIAGNOSTICO_FINAL,
          TO_CHAR(CIEFINAL.NOMBRE)                    AS DIAGNOSTICO_FINAL,
          TO_CHAR(DIA.OBSERVACION)                    AS OBSERVACION,
          TO_CHAR(TRATOCASO.DESCRIPCION )              AS TIPO_CASO,
          TO_CHAR(EPI.FECHAINVESTIGACION,'yyyy-mm-dd')    AS FECHA_INVESTIGACION,
          TO_CHAR(EPI.FECHACIERRECASO, 'yyyy-mm-dd')                AS FECHA_CIERRE_CASO,
          TO_CHAR(PERMODIFI.NOMBRECOMPLETO)           AS RESPONSABLE_EPIDEMIOLOGIA,
          TO_CHAR(DEFINICION.DESCRIPCION)             AS CUMPLE_DEFINICION,
          TO_CHAR(EPI.FECHADEFINIOCASO ,'yyyy-mm-dd')               AS FECHA_DEFINIO_CASO,
          TO_CHAR(EPI.MOTIVOCUMPLEDEFINICION)         AS MOTIVO_DEFINICION_CASO,
         
         -- FI.DETALLEFACTORRIESGO             AS FACTORRIESGO,
          TO_CHAR(DEFINIO.NOMBRECOMPLETO)             AS MEDICO_DEFINIO_CASO,
          TO_CHAR(EPM.NOMBRE)                         AS NOMBRE_MUESTRA,
          TO_CHAR(det.DESCRIPCION)                    AS TIPO_MUESTRA,
          TO_CHAR(EPM.FECHATOMA, 'yyyy-mm-dd')               AS FECHA_TOMA,
          TO_CHAR(EPM.FECHACREACION, 'yyyy-mm-dd')           AS FECHA_SOLICITUD,
          TO_CHAR(EPM.FECHAENVIO, 'yyyy-mm-dd')              AS FECHA_ENVIO,
          TO_CHAR(EPRM.FECHARECEPCION, 'yyyy-mm-dd')         AS FECHA_RECEPCION,
          TO_CHAR(EPRM.FECHAPROCESAMIENTO, 'yyyy-mm-dd')     AS FECHA_PROCESAMIENTO,
          TO_CHAR(EPRM.FECHAENTREGARESULTADOS, 'yyyy-mm-dd') AS FECHA_ENTREGA_RESULTADOS,
          TO_CHAR(EPRM.MUESTRAADECUADA) 						         AS MUSTRA_ADECUADA, 
          TO_CHAR(det2.DESCRIPCION) AS RESULTADO_MUESTRA,
          CASE EPM.ESTADO
          WHEN  0 THEN 'Muestra(s) enviada(s)'
          WHEN  1 THEN 'Procesando muestra(s)'
          WHEN  2 THEN 'Analizando muestra(s)'
          WHEN  3 THEN 'Muestra analizada'
          WHEN  4 THEN 'Muestra rechazada'
          WHEN  5 THEN 'Muestra rechazada por no envio'
          WHEN  6 THEN 'Muestra rechazada por no adecuada'
          ELSE '-'
          END AS ESTADO_MUESTRA
     FROM HCUE_VIGILANCIA.EPINDIVIDUAL EPI  
 	   INNER JOIN HCUE_VIGILANCIA.FICHAINVESTIGACION FI                  ON FI.EPINDIVIDUAL_ID = EPI.ID 
       LEFT JOIN HCUE_AMED.DIAGNOSTICOATENCION DIA                       ON EPI.DIAGNOSTICOATENCION_ID = DIA.ID 
       LEFT JOIN HCUE_CATALOGOS.CIE CIE                                  ON DIA.CIE_ID = CIE.ID --AND CIE.ACTIVO=1
       LEFT JOIN HCUE_CATALOGOS.CIE CIEFINAL                             ON EPI.DIAGNOSTICOFINALCIE_ID = CIEFINAL.ID --AND CIEFINAL.ACTIVO=1
       LEFT JOIN HCUE_VIGILANCIA.SEMANAEPI SE                            ON EPI.SEMANAEPI_ID = SE.ID
       LEFT JOIN HCUE_VIGILANCIA.SEMANAEPI SECREACION                    ON EPI.SEMANAEPICREACION_ID = SECREACION.ID
       LEFT JOIN HCUE_AMED.ATENCIONMEDICA AMED                           ON DIA.ATENCIONMEDICA_ID = AMED.ID 
       LEFT JOIN HCUE_SISTEMA.ENTIDAD ENTIDAD                            ON AMED.ENTIDAD_ID = ENTIDAD.ID
       LEFT JOIN HCUE_CATALOGOS.ORGANICO ORG                             ON ORG.ID = ENTIDAD.ORGANICO_ID
       LEFT JOIN HCUE_CATALOGOS.ORGANICO ORG1                            ON ORG1.ID= ORG.ORGANICO_ID
       LEFT JOIN HCUE_CATALOGOS.ORGANICO ORG2                            ON ORG2.ID = ORG1.ORGANICO_ID
       LEFT JOIN HCUE_AMED.PACIENTE PAC                                  ON AMED.PACIENTE_ID = PAC.ID
       LEFT JOIN HCUE_SISTEMA.PERSONA PER                                ON PAC.PERSONA_ID = PER.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO SEX                      ON PER.CTSEXO_ID = SEX.ID
       LEFT JOIN HCUE_SISTEMA.USUARIO DEFINIOUSUARIO                     ON EPI.USUARIODEFINIOCASO_ID = DEFINIOUSUARIO.ID
       LEFT JOIN HCUE_SISTEMA.PERSONA DEFINIO                            ON DEFINIOUSUARIO.PERSONA_ID = DEFINIO.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO ETNIA                    ON PAC.CTETNIA_ID = ETNIA.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO NACIONALIDADETNICA       ON PAC.CTNACIONALIDADETNICA_ID = NACIONALIDADETNICA.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO CIVIL                    ON PER.CTESTADOCIVIL_ID = CIVIL.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO EDUCACION                ON PER.CTNIVELEDUCACION_ID = EDUCACION.ID
       LEFT JOIN HCUE_CATALOGOS.PROFESION PROFESION                      ON PAC.PROFESION_ID = PROFESION.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO CTTIPO                   ON PER.CTTIPOIDENTIFICACION_ID = CTTIPO.ID
       LEFT JOIN HCUE_CATALOGOS.CIRCUITO CIRCUITOENT                     ON ENTIDAD.CIRCUITO_ID = CIRCUITOENT.ID
       LEFT JOIN HCUE_CATALOGOS.DISTRITO DISTRITOENT                     ON CIRCUITOENT.DISTRITO_ID = DISTRITOENT.ID
       LEFT JOIN HCUE_CATALOGOS.ZONA ZONAENT                             ON DISTRITOENT.ZONA_ID = ZONAENT.ID
       LEFT JOIN HCUE_CATALOGOS.PARROQUIA PARROQUIAENT                   ON ENTIDAD.PARROQUIA_ID = PARROQUIAENT.ID
       LEFT JOIN HCUE_CATALOGOS.CANTON CANTONENT                         ON PARROQUIAENT.CANTON_ID = CANTONENT.ID
       LEFT JOIN HCUE_CATALOGOS.PROVINCIA PROVINCIAENT                   ON CANTONENT.PROVINCIA_ID = PROVINCIAENT.ID
       LEFT JOIN HCUE_CATALOGOS.PAIS PAIS                                ON PER.PAIS_ID = PAIS.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO AREA                     ON PARROQUIAENT.CTTIPO_ID = AREA.ID
       LEFT JOIN HCUE_CATALOGOS.PARROQUIA PACPARROQUIA                   ON PAC.PARROQUIA_ID = PACPARROQUIA.ID
       LEFT JOIN HCUE_CATALOGOS.CANTON PACCANTON                         ON PACPARROQUIA.CANTON_ID = PACCANTON.ID
       LEFT JOIN HCUE_CATALOGOS.PROVINCIA PACPROVINCIA                   ON PACCANTON.PROVINCIA_ID = PACPROVINCIA.ID
       LEFT JOIN HCUE_CATALOGOS.PARROQUIA INFECPARR                      ON EPI.PARROQUIA_ID = INFECPARR.ID
       LEFT JOIN HCUE_CATALOGOS.CANTON INFECCIONCANTON                   ON EPI.CANTON_ID = INFECCIONCANTON.ID
       LEFT JOIN HCUE_CATALOGOS.PROVINCIA INFECPRO                       ON EPI.PROVINCIA_ID = INFECPRO.ID
       LEFT JOIN HCUE_CATALOGOS.PAIS INFECCIONPAIS                       ON EPI.PAIS_ID = INFECCIONPAIS.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO DEFINICION               ON EPI.CUMPLEDEFINICION_ID = DEFINICION.ID
       LEFT JOIN HCUE_VIGILANCIA.EPRESULTADOCASO RESULTADOCASO           ON EPI.EPRESULTADOCASO_ID = RESULTADOCASO.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO RESULTADO                ON RESULTADOCASO.CTRESULTADOEPI_ID = RESULTADO.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO CONDICIONEGRESO          ON FI.CTCONDICIONEGRESO_ID = CONDICIONEGRESO.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO CLASIFICACIONCASO        ON FI.CTCLASIFICACIONCASO_ID = CLASIFICACIONCASO.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO CLASIFICACIONFINAL       ON EPI.CTCLASIFICACIONFINAL_ID = CLASIFICACIONFINAL.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO CONFIRMADOPOR            ON EPI.CTCONFIRMADOPOR_ID = CONFIRMADOPOR.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO TRATOCASO                ON FI.CTTRATOCASO_ID = TRATOCASO.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO SERVICIO                 ON FI.CTSERVICIO_ID = SERVICIO.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO LUGARATENCION            ON EPI.CTLUGARATENCION_ID = LUGARATENCION.ID
       LEFT JOIN HCUE_SISTEMA.USUARIO USUARIOCREACION                    ON EPI.USUARIOCREACION_ID = USUARIOCREACION.ID
       LEFT JOIN HCUE_SISTEMA.PERSONA PERSONACREACION                    ON USUARIOCREACION.PERSONA_ID = PERSONACREACION.ID
       LEFT JOIN HCUE_SISTEMA.USUARIO USUARIOMODIFICACION                ON EPI.USUARIOMODIFICACION_ID = USUARIOMODIFICACION.ID
       LEFT JOIN HCUE_SISTEMA.PERSONA PERMODIFI                          ON USUARIOMODIFICACION.PERSONA_ID = PERMODIFI.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO CONDICIONDIAGNOSTICO     ON DIA.CTCONDICIONDIAGNOSTICO_ID = CONDICIONDIAGNOSTICO.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO CRONOLOGIADIAGNOSTICO    ON DIA.CTCRONOLOGIADIAGNOSTICO_ID = CRONOLOGIADIAGNOSTICO.ID
       LEFT JOIN HCUE_VIGILANCIA.EPIMUESTRA EPM 						 ON EPM.EPINDIVIDUAL_ID = EPI.ID
       LEFT  OUTER JOIN HCUE_CATALOGOS.DETALLECATALOGO det               ON det.ID = EPM.CTDETALLECATALOGO_ID 
       LEFT JOIN HCUE_VIGILANCIA.EPRESULTADOMUESTRA EPRM				 ON EPRM.EPIMUESTRA_ID = EPM.ID
       LEFT OUTER JOIN HCUE_CATALOGOS.DETALLECATALOGO det2               ON det2.ID = EPRM.CTRESULTADOMUESTRA_ID 
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO CTGS                     ON CTGS.ID = PAC.CTGRUPOSANGUINEO_ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO CTDIS                    ON CTDIS.ID = PAC.CTDISCAPACIDAD_ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO PUEBLO                   ON PUEBLO.ID = PAC.CTPUEBLO_ID
       
       LEFT JOIN (SELECT COUNT(*) EXPUESTO,FICHAINVESTIGACION_ID FROM  HCUE_VIGILANCIA.DETALLEPERSONAEXPUESTA WHERE ACTIVO =1 GROUP BY FICHAINVESTIGACION_ID) DPE ON FI.ID = DPE.FICHAINVESTIGACION_ID 
 	   LEFT JOIN (SELECT COUNT(*) EXPUESTOALTORIESGO,FICHAINVESTIGACION_ID FROM  HCUE_VIGILANCIA.DETALLEPERSONAEXPUESTA WHERE ALTORIESGO = 1 AND ACTIVO =1 GROUP BY FICHAINVESTIGACION_ID) DPE ON FI.ID = DPE.FICHAINVESTIGACION_ID
 	   
 	   LEFT JOIN (SELECT ANTFR.FICHAINVESTIGACION_ID, LISTAGG(DETCATANT.DESCRIPCION, ',') WITHIN GROUP(ORDER BY ANTFR.FICHAINVESTIGACION_ID) AS FACTOR_RIESGO
	   FROM HCUE_VIGILANCIA.ANTFACTORRIESGO ANTFR  
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO DETCATANT ON ANTFR.FACTORRIESGO_ID = DETCATANT.ID WHERE ANTFR.ACTIVO=1 GROUP BY ANTFR.FICHAINVESTIGACION_ID) AFR ON AFR.FICHAINVESTIGACION_ID = FI.ID  
 	   
       LEFT JOIN (SELECT ANMDT.FICHAINVESTIGACION_ID, LISTAGG(DETCATMDT.DESCRIPCION, ',') WITHIN GROUP(ORDER BY ANMDT.FICHAINVESTIGACION_ID) AS MODO_TRANSMISION
	   FROM HCUE_VIGILANCIA.ANTMODOTRANSMISION ANMDT  
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO DETCATMDT ON ANMDT.MODOTRANSMISION_ID = DETCATMDT.ID WHERE ANMDT.ACTIVO=1 GROUP BY ANMDT.FICHAINVESTIGACION_ID) AMDT ON AMDT.FICHAINVESTIGACION_ID = FI.ID  
 	   
       LEFT JOIN (SELECT DTSIN.FICHAINVESTIGACION_ID, LISTAGG(DETCATMDT.DESCRIPCION, ',') WITHIN GROUP(ORDER BY DTSIN.FICHAINVESTIGACION_ID) AS SIGNOS_SINTOMAS
	   FROM HCUE_VIGILANCIA.DETALLESINTOMA DTSIN  
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO DETCATMDT ON DTSIN.CTSINTOMA_ID = DETCATMDT.ID WHERE DTSIN.ACTIVO=1 GROUP BY DTSIN.FICHAINVESTIGACION_ID) SYS ON SYS.FICHAINVESTIGACION_ID = FI.ID  
 	   
      );
/*TABLA VP_EPINDIVIDUAL_HISTORICO*/
SELECT
	ID AS EPINDIVIDUAL_ID,
	TO_CHAR('N/A') AS FICHA_INVESTIGACION_ID ,
	 TO_CHAR(V1_ANIO )  AS AÑO,
	TO_CHAR('N/A')   AS MES,
	V14_FECATENCION  AS FECHA_ATENCION,
	V3_INSTITUCION AS INSTITUCION,
	TO_CHAR('N/A') AS INSTITUCION_ID,
	V4_UNIDADOPERATIVA AS ESTABLECIMIENTO,
	V5_UNICODIGO  AS UNICODIGO,
	V6_ZONA AS ZONA,
	TO_CHAR('N/A') AS ZONAENT_ID,
	 TO_CHAR('N/A')AS ZONA_CODIGO,
	 TO_CHAR('N/A') AS CODIGO_DISTRITO,
	 TO_CHAR('N/A') AS DISTRITOENT_ID,
	V7_DISTRITO AS DISTRITO,
	V8_CODPROVINCIA AS CODIGO_PROVINCIA,
	V9_PROVINCIA AS PROVINCIA,
	V10_CODCANTON AS CODIGO_CANTON,
	V11_CANTON AS CANTON,
	V12_CODPARROQUIA AS CODIGO_PARROQUIA,
	V13_PARROQUIA AS PARROQUIA,
	TO_CHAR('N/A') AS AREA_SECTOR,
	V32_INICIODESINTOMAS AS FECHA_INICIO_SINTOMA,
	V2_FECNOTIF AS FECHA_NOTIFICACION,
	V33_SE AS SEMANA_EPIDEMIOLOGICA1,
	TO_CHAR('N/A') AS SEMANAEPI_ID,
	TO_CHAR('N/A') AS SEMANAEPI_ANIO,
	TO_CHAR('N/A') AS NOMBRE_NOTIFICA,
	V15_PACIENTE AS NOMBRE_PACIENTE,
	TO_CHAR('N/A') AS TIPO_IDENTIFICACION,
	V16_NOIDENTIFICACION AS NUMERO_IDENTIFICACION,
	V17_HISTORIACLINICA AS NUMERO_HISTORIA_CLINICA,
	V18_NACIONALIDAD AS NACIONALIDAD,
	V31_AUTOIDENTIFICACION AS  AUTOIDENTIFICACION_ETNICA,
	TO_CHAR('N/A') AS NACIONALIDAD_ETNICA,
	V26_SEXO AS SEXO,
	V43_EMBARAZADA AS EMBARAZADA,
	V44_SEMANASGESTACION AS SEMANA_GESTACION,
	TO_CHAR('N/A') AS CODIGO_PAIS,
	 TO_CHAR('N/A') AS PAIS,
	TO_CHAR('N/A') AS ESTADO_CIVIL,
	TO_CHAR('N/A') AS FECHA_NACIMIENTO,
	V27_EDAD AS EDAD,
	V28_TIPOEDAD AS TIPO_EDAD,
	V29_GRUPOEDAD AS GRUPO_EDAD,
	TO_CHAR('N/A') AS NIVEL_EDUCACION,
	V30_OCUPACION AS OCUPACION,
	V19_CODPROVDOMIC AS CODIGO_PROVINCIA_RESIDENCIA,
	V20_PROVDOMIC AS PROVINCIA_RESIDENCIA,
	V21_CODCANTONDOMIC AS CODIGO_CANTON_RESIDENCIA ,
	V22_CANTONDOMIC AS CANTON_RESIDENCIA,
	V23_CODPARROQDOMIC AS CODIGO_PARROQUIA_RESIDENCIA,
	V24_PARROQDOMIC AS PARROQUIA_RESIDENCIA,
	V25_TELEFONO AS TELEFONO,
	TO_CHAR('N/A')AS PACIENTE_ID,
	TO_CHAR('N/A') AS BARRIO,
	TO_CHAR('N/A') AS CALLEPRINCIPAL,
    TO_CHAR('N/A') AS CALLESECUNDARIA,
    TO_CHAR('N/A') AS NUMERORESIDENCIA,
    TO_CHAR('N/A') AS GRUPOSANGUINEO,
     TO_CHAR('N/A')             AS CODIGO_PAIS_INFECCION,
     TO_CHAR('N/A')             AS PAIS_INFECCION,
     TO_CHAR('N/A')            AS CODIGO_PROVINCIA_INFECCION,
     TO_CHAR('N/A')             AS PROVINCIA_INFECCION,
     TO_CHAR('N/A')       AS CODIGO_CANTON_INFECCION,
     TO_CHAR('N/A')      AS CANTON_INFECCION,
     TO_CHAR('N/A')            AS CODIGO_PARROQUIA_INFECCION,
     TO_CHAR('N/A')            AS PARROQUIA_INFECCION,
      TO_CHAR('N/A')          AS LUGAR_PROBABLE_INFECCION,
     TO_CHAR('N/A')                 AS SEMANA_EPIDEMIOLOGICA2,
     TO_CHAR('N/A')                       AS CODIGOCIE1O,
	V34_DIAGNOSTICOINICIAL AS DIAGNOSTICO_INICIAL,
	 TO_CHAR('N/A') AS CODIGO_DIAGNOSTICO_INICIAL,
	 TO_CHAR('N/A') AS NOTIFICACIONOBLIGATORIA,
	  TO_CHAR('N/A') AS CONDICION,
	V73_CONDICIONFINAL AS CONDICION_FINAL,
      TO_CHAR('N/A') AS CRONOLOGIA,
		V70_CONTACTOS AS CONTACTOS_EXPUESTOS,
	V71_CONTACTOSALTORIESGO AS CONTACTOS_ALTORIESGO,
	 TO_CHAR('N/A') AS NUMCASOSGENERAL,
	V38_LUGARVIAJE AS LUGAR_VIAJE,
	 TO_CHAR('N/A') AS FECHA_INICIOVIAJE,
	V37_ULTIMAFECHA AS FECHA_FINAL_VIAJE,
	V36_ANTECEDENTEVIAJE AS ANTECEDENTEVIAJE,
	  TO_CHAR('N/A') AS NOMBRE_REPRESENTANTE,
	 TO_CHAR('N/A') AS  TELEFONOCONTACTO,
	 TO_CHAR('N/A') AS DIRECCIONCONTACTO,
	 TO_CHAR('N/A')                 AS DISCAPACIDAD,
     TO_CHAR('N/A')				 AS PUEBLO,
    V45_MUESTRA AS LABORATORIO,
    V47_RESULTADOLAB AS RESULTADO,
	V35_COMORBILIDAD AS COMORBILIDAD,
	 TO_CHAR('N/A') AS PRESENCIACOMORBILIDAD,
	 TO_CHAR('N/A') AS MODO_TRANSMISION,
	 TO_CHAR('N/A') AS FACTOR_RIESGO,
	 TO_CHAR('N/A') AS SIGNOS_SINTOMAS,
	 TO_CHAR('N/A') AS HOSPITALIZADO,
	 TO_CHAR('N/A')  AS SERVICIO,
	 TO_CHAR('N/A') AS CONDICION_EGRESO,
	 TO_CHAR('N/A') AS  CLASIFICACION_CASO,
	 TO_CHAR('N/A') AS CTCLASIFICACIONCASO_ID,
	V77_CLASIFICACIONFINALDELCASO AS CLASIFICACION_FINAL_CASO,
	V72_LUGARDEATENCION AS LUGAR_ATENCION,
    V76_FECFALLEC AS FECHA_FALLECIMIENTO,
    V80_CONFIRMADOPOR AS CONFIRMADO_POR,
     TO_CHAR('N/A') AS CODIGO_DIAGNOSTICO_FINAL,
    V78_DIAGNOSTICOFINAL AS DIAGNOSTICO_FINAL,
    V68_OBSERVACIONES AS OBSERVACION,
    V81_TIPO AS TIPO_CASO,
    V69_FECINVESTIGACION AS FECHA_INVESTIGACION,
    V82_FECCIERRE AS FECHA_CIERRE_CASO,
    V83_EPIDEMIOLOGO AS RESPONSABLE_EPIDEMIOLOGIA,
     TO_CHAR('N/A') AS CUMPLE_DEFINICION,
     TO_CHAR('N/A')            AS FECHA_DEFINIO_CASO,
     TO_CHAR('N/A')       AS MOTIVO_DEFINICION_CASO,
     TO_CHAR('N/A') AS MEDICO_DEFINIO_CASO,
	V48_MUESTRA1 AS NOMBRE_MUESTRA,
	 TO_CHAR('N/A') AS TIPO_MUESTRA,
	V49_FECTOMA1 AS FECHA_TOMA,
	 TO_CHAR('N/A') AS FECHA_SOLICITUD,
	  TO_CHAR('N/A') AS FECHA_ENVIO,
	V50_FECHARECIBO1 AS FECHA_RECEPCION,
	V52_FECPROC1 AS FECHA_PROCESAMIENTO,
	 TO_CHAR('N/A') AS FECHA_ENTREGA_RESULTADOS,
	V51_ADECUADAM1 AS MUSTRA_ADECUADA,
	TO_CHAR('N/A') AS RESULTADO_MUESTRA,
	 TO_CHAR('N/A') AS ESTADO_MUESTRA	
FROM
	HCUE_VIGILANCIA.VIEPI_HISTORICO_INDIVIDUAL
   ;
 

    
    SELECT  COUNT(*) FROM HCUE_VIGILANCIA.VIEPI_HISTORICO_INDIVIDUAL; 




SELECT o3.* FROM HCUE_SISTEMA.ENTIDAD e 
INNER JOIN HCUE_CATALOGOS.ORGANICO o ON o.id=e.ORGANICO_ID 
INNER JOIN HCUE_CATALOGOS.ORGANICO o2 ON o2.id = o.ORGANICO_ID 
INNER JOIN HCUE_CATALOGOS.ORGANICO o3 ON o3.ID =o2.ORGANICO_ID
WHERE o3.NIVEL =6;



/*
CASE  
WHEN TRUNC(months_between(sysdate, pni.FECHANACIMIENTO) / 12)  < 1 AND  trunc(mod(months_between(sysdate,pni.FECHANACIMIENTO),12)) < 1 AND trunc(sysdate-add_months(pni.FECHANACIMIENTO ,trunc(months_between(sysdate,pni.FECHANACIMIENTO)/12)*12+trunc(mod(months_between(sysdate,pni.FECHANACIMIENTO),12)))) <=28    THEN 'De 0 a 28 días' 
WHEN   TRUNC(months_between(sysdate, pni.FECHANACIMIENTO) / 12)  < 1 AND trunc(mod(months_between(sysdate,pni.FECHANACIMIENTO),12)) >= 1 AND trunc(mod(months_between(sysdate,pni.FECHANACIMIENTO),12)) <=11  THEN 'De 1 a 11 meses'
WHEN  TRUNC(months_between(sysdate, pni.FECHANACIMIENTO) / 12)  >=1 AND TRUNC(months_between(sysdate, pni.FECHANACIMIENTO) / 12) <=4  THEN 'De 1 a 4 años'
WHEN   TRUNC(months_between(sysdate, pni.FECHANACIMIENTO) / 12)  >=5 AND TRUNC(months_between(sysdate, pni.FECHANACIMIENTO) / 12) <=9  THEN 'De 5 a 9 años'
WHEN  TRUNC(months_between(sysdate, pni.FECHANACIMIENTO) / 12)  >=10 AND TRUNC(months_between(sysdate, pni.FECHANACIMIENTO) / 12) <=14  THEN 'De 10 a 14 años'
WHEN  TRUNC(months_between(sysdate, pni.FECHANACIMIENTO) / 12)  >=15 AND TRUNC(months_between(sysdate, pni.FECHANACIMIENTO) / 12) <=19  THEN 'De 15 a 19 años'
WHEN   TRUNC(months_between(sysdate, pni.FECHANACIMIENTO) / 12)  >=15 AND TRUNC(months_between(sysdate, pni.FECHANACIMIENTO) / 12) <=19  THEN 'De 15 a 19 años'
WHEN   TRUNC(months_between(sysdate, pni.FECHANACIMIENTO) / 12)  >=20 AND TRUNC(months_between(sysdate, pni.FECHANACIMIENTO) / 12) <=39  THEN 'De 20 a 39 años'
WHEN   TRUNC(months_between(sysdate, pni.FECHANACIMIENTO) / 12)  >=40 AND TRUNC(months_between(sysdate, pni.FECHANACIMIENTO) / 12) <=64  THEN 'De 40 a 64 años'
WHEN  TRUNC(months_between(sysdate, pni.FECHANACIMIENTO) / 12)  >=65   THEN 'Mayor de 65 años'
ELSE  'No hay edad'
END  GRUPO_EDAD,*/




 

SELECT  COUNT(*) 
  FROM HCUE_VIGILANCIA.EPINDIVIDUAL EPI  
 	   INNER JOIN HCUE_VIGILANCIA.FICHAINVESTIGACION FI                  ON FI.EPINDIVIDUAL_ID = EPI.ID 
       LEFT JOIN HCUE_AMED.DIAGNOSTICOATENCION DIA                       ON EPI.DIAGNOSTICOATENCION_ID = DIA.ID 
       LEFT JOIN HCUE_CATALOGOS.CIE CIE                                  ON DIA.CIE_ID = CIE.ID --AND CIE.ACTIVO=1
       LEFT JOIN HCUE_CATALOGOS.CIE CIEFINAL                             ON EPI.DIAGNOSTICOFINALCIE_ID = CIEFINAL.ID --AND CIEFINAL.ACTIVO=1
       LEFT JOIN HCUE_VIGILANCIA.SEMANAEPI SE                            ON EPI.SEMANAEPI_ID = SE.ID
       LEFT JOIN HCUE_VIGILANCIA.SEMANAEPI SECREACION                    ON EPI.SEMANAEPICREACION_ID = SECREACION.ID
       LEFT JOIN HCUE_AMED.ATENCIONMEDICA AMED                           ON DIA.ATENCIONMEDICA_ID = AMED.ID 
       LEFT JOIN HCUE_SISTEMA.ENTIDAD ENTIDAD                            ON AMED.ENTIDAD_ID = ENTIDAD.ID
       LEFT JOIN HCUE_CATALOGOS.ORGANICO ORG                             ON ORG.ID = ENTIDAD.ORGANICO_ID
       LEFT JOIN HCUE_CATALOGOS.ORGANICO ORG1                            ON ORG1.ID= ORG.ORGANICO_ID
       LEFT JOIN HCUE_CATALOGOS.ORGANICO ORG2                            ON ORG2.ID = ORG1.ORGANICO_ID
       LEFT JOIN HCUE_AMED.PACIENTE PAC                                  ON AMED.PACIENTE_ID = PAC.ID
       LEFT JOIN HCUE_SISTEMA.PERSONA PER                                ON PAC.PERSONA_ID = PER.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO SEX                      ON PER.CTSEXO_ID = SEX.ID
       LEFT JOIN HCUE_SISTEMA.USUARIO DEFINIOUSUARIO                     ON EPI.USUARIODEFINIOCASO_ID = DEFINIOUSUARIO.ID
       LEFT JOIN HCUE_SISTEMA.PERSONA DEFINIO                            ON DEFINIOUSUARIO.PERSONA_ID = DEFINIO.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO ETNIA                    ON PAC.CTETNIA_ID = ETNIA.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO NACIONALIDADETNICA       ON PAC.CTNACIONALIDADETNICA_ID = NACIONALIDADETNICA.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO CIVIL                    ON PER.CTESTADOCIVIL_ID = CIVIL.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO EDUCACION                ON PER.CTNIVELEDUCACION_ID = EDUCACION.ID
       LEFT JOIN HCUE_CATALOGOS.PROFESION PROFESION                      ON PAC.PROFESION_ID = PROFESION.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO CTTIPO                   ON PER.CTTIPOIDENTIFICACION_ID = CTTIPO.ID
       LEFT JOIN HCUE_CATALOGOS.CIRCUITO CIRCUITOENT                     ON ENTIDAD.CIRCUITO_ID = CIRCUITOENT.ID
       LEFT JOIN HCUE_CATALOGOS.DISTRITO DISTRITOENT                     ON CIRCUITOENT.DISTRITO_ID = DISTRITOENT.ID
       LEFT JOIN HCUE_CATALOGOS.ZONA ZONAENT                             ON DISTRITOENT.ZONA_ID = ZONAENT.ID
       LEFT JOIN HCUE_CATALOGOS.PARROQUIA PARROQUIAENT                   ON ENTIDAD.PARROQUIA_ID = PARROQUIAENT.ID
       LEFT JOIN HCUE_CATALOGOS.CANTON CANTONENT                         ON PARROQUIAENT.CANTON_ID = CANTONENT.ID
       LEFT JOIN HCUE_CATALOGOS.PROVINCIA PROVINCIAENT                   ON CANTONENT.PROVINCIA_ID = PROVINCIAENT.ID
       LEFT JOIN HCUE_CATALOGOS.PAIS PAIS                                ON PER.PAIS_ID = PAIS.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO AREA                     ON PARROQUIAENT.CTTIPO_ID = AREA.ID
       LEFT JOIN HCUE_CATALOGOS.PARROQUIA PACPARROQUIA                   ON PAC.PARROQUIA_ID = PACPARROQUIA.ID
       LEFT JOIN HCUE_CATALOGOS.CANTON PACCANTON                         ON PACPARROQUIA.CANTON_ID = PACCANTON.ID
       LEFT JOIN HCUE_CATALOGOS.PROVINCIA PACPROVINCIA                   ON PACCANTON.PROVINCIA_ID = PACPROVINCIA.ID
       LEFT JOIN HCUE_CATALOGOS.PARROQUIA INFECPARR                      ON EPI.PARROQUIA_ID = INFECPARR.ID
       LEFT JOIN HCUE_CATALOGOS.CANTON INFECCIONCANTON                   ON EPI.CANTON_ID = INFECCIONCANTON.ID
       LEFT JOIN HCUE_CATALOGOS.PROVINCIA INFECPRO                       ON EPI.PROVINCIA_ID = INFECPRO.ID
       LEFT JOIN HCUE_CATALOGOS.PAIS INFECCIONPAIS                       ON EPI.PAIS_ID = INFECCIONPAIS.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO DEFINICION               ON EPI.CUMPLEDEFINICION_ID = DEFINICION.ID
       LEFT JOIN HCUE_VIGILANCIA.EPRESULTADOCASO RESULTADOCASO           ON EPI.EPRESULTADOCASO_ID = RESULTADOCASO.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO RESULTADO                ON RESULTADOCASO.CTRESULTADOEPI_ID = RESULTADO.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO CONDICIONEGRESO          ON FI.CTCONDICIONEGRESO_ID = CONDICIONEGRESO.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO CLASIFICACIONCASO        ON FI.CTCLASIFICACIONCASO_ID = CLASIFICACIONCASO.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO CLASIFICACIONFINAL       ON EPI.CTCLASIFICACIONFINAL_ID = CLASIFICACIONFINAL.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO CONFIRMADOPOR            ON EPI.CTCONFIRMADOPOR_ID = CONFIRMADOPOR.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO TRATOCASO                ON FI.CTTRATOCASO_ID = TRATOCASO.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO SERVICIO                 ON FI.CTSERVICIO_ID = SERVICIO.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO LUGARATENCION            ON EPI.CTLUGARATENCION_ID = LUGARATENCION.ID
       LEFT JOIN HCUE_SISTEMA.USUARIO USUARIOCREACION                    ON EPI.USUARIOCREACION_ID = USUARIOCREACION.ID
       LEFT JOIN HCUE_SISTEMA.PERSONA PERSONACREACION                    ON USUARIOCREACION.PERSONA_ID = PERSONACREACION.ID
       LEFT JOIN HCUE_SISTEMA.USUARIO USUARIOMODIFICACION                ON EPI.USUARIOMODIFICACION_ID = USUARIOMODIFICACION.ID
       LEFT JOIN HCUE_SISTEMA.PERSONA PERMODIFI                          ON USUARIOMODIFICACION.PERSONA_ID = PERMODIFI.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO CONDICIONDIAGNOSTICO     ON DIA.CTCONDICIONDIAGNOSTICO_ID = CONDICIONDIAGNOSTICO.ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO CRONOLOGIADIAGNOSTICO    ON DIA.CTCRONOLOGIADIAGNOSTICO_ID = CRONOLOGIADIAGNOSTICO.ID
       LEFT JOIN HCUE_VIGILANCIA.EPIMUESTRA EPM 						 ON EPM.EPINDIVIDUAL_ID = EPI.ID
       LEFT  OUTER JOIN HCUE_CATALOGOS.DETALLECATALOGO det               ON det.ID = EPM.CTDETALLECATALOGO_ID 
       LEFT JOIN HCUE_VIGILANCIA.EPRESULTADOMUESTRA EPRM				 ON EPRM.EPIMUESTRA_ID = EPM.ID
       LEFT OUTER JOIN HCUE_CATALOGOS.DETALLECATALOGO det2               ON det2.ID = EPRM.CTRESULTADOMUESTRA_ID 
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO CTGS                     ON CTGS.ID = PAC.CTGRUPOSANGUINEO_ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO CTDIS                    ON CTDIS.ID = PAC.CTDISCAPACIDAD_ID
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO PUEBLO                   ON PUEBLO.ID = PAC.CTPUEBLO_ID
       
       LEFT JOIN (SELECT COUNT(*) EXPUESTO,FICHAINVESTIGACION_ID FROM  HCUE_VIGILANCIA.DETALLEPERSONAEXPUESTA WHERE ACTIVO =1 GROUP BY FICHAINVESTIGACION_ID) DPE ON FI.ID = DPE.FICHAINVESTIGACION_ID 
 	   LEFT JOIN (SELECT COUNT(*) EXPUESTOALTORIESGO,FICHAINVESTIGACION_ID FROM  HCUE_VIGILANCIA.DETALLEPERSONAEXPUESTA WHERE ALTORIESGO = 1 AND ACTIVO =1 GROUP BY FICHAINVESTIGACION_ID) DPE ON FI.ID = DPE.FICHAINVESTIGACION_ID
 	   
 	   LEFT JOIN (SELECT ANTFR.FICHAINVESTIGACION_ID, LISTAGG(DETCATANT.DESCRIPCION, ',') WITHIN GROUP(ORDER BY ANTFR.FICHAINVESTIGACION_ID) AS FACTOR_RIESGO
	   FROM HCUE_VIGILANCIA.ANTFACTORRIESGO ANTFR  
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO DETCATANT ON ANTFR.FACTORRIESGO_ID = DETCATANT.ID WHERE ANTFR.ACTIVO=1 GROUP BY ANTFR.FICHAINVESTIGACION_ID) AFR ON AFR.FICHAINVESTIGACION_ID = FI.ID  
 	   
       LEFT JOIN (SELECT ANMDT.FICHAINVESTIGACION_ID, LISTAGG(DETCATMDT.DESCRIPCION, ',') WITHIN GROUP(ORDER BY ANMDT.FICHAINVESTIGACION_ID) AS MODO_TRANSMISION
	   FROM HCUE_VIGILANCIA.ANTMODOTRANSMISION ANMDT  
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO DETCATMDT ON ANMDT.MODOTRANSMISION_ID = DETCATMDT.ID WHERE ANMDT.ACTIVO=1 GROUP BY ANMDT.FICHAINVESTIGACION_ID) AMDT ON AMDT.FICHAINVESTIGACION_ID = FI.ID  
 	   
       LEFT JOIN (SELECT DTSIN.FICHAINVESTIGACION_ID, LISTAGG(DETCATMDT.DESCRIPCION, ',') WITHIN GROUP(ORDER BY DTSIN.FICHAINVESTIGACION_ID) AS SIGNOS_SINTOMAS
	   FROM HCUE_VIGILANCIA.DETALLESINTOMA DTSIN  
       LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO DETCATMDT ON DTSIN.CTSINTOMA_ID = DETCATMDT.ID WHERE DTSIN.ACTIVO=1 GROUP BY DTSIN.FICHAINVESTIGACION_ID) SYS ON SYS.FICHAINVESTIGACION_ID = FI.ID  
 	   
       WHERE EPI.ACTIVO = 1 AND DIA.ACTIVO = 1 AND AMED.CTESTADO_ID=222;

SELECT  COUNT(*) 
  FROM HCUE_VIGILANCIA.EPINDIVIDUAL EPI;
 
 
/* Consulta epi_grupal*/
SELECT g.ID, ec.ID AS IDM,ec.FECINI,ec.FECFIN,ec.RESPONSABLE,
ec.CARGO,ec.FECHAR,ec.TOTALCONSULTAS AS TOTALCONSULTAS_CABECERA,ec.NOTNEG,
ec.TOTALHOMBRES AS TOTALHOMBRES_cabecera,
ec.TOTALMUJERES AS TOTALMUJERES_CABECERA,ec.HOMBRES AS HOMBRES_CABECERA,
ec.MUJERES AS MUJERES_CABECERA,ec.TOTAL AS TOTAL_CABECERA
,g.ANIO, g.ESTABLE, g.IDE,   
g.G0M, g.G0F,
g.G1M, g.G1F,
g.G4M, g.G4F,
g.G9M, g.G9F, 
g.G14M, g.G14F,
g.G19M, g.G19F,
g.G39M, g.G39F,
g.G64M, g.G64F,
g.G65M, g.G65F,
g.NOTINEG, g.IPINGRE, g.IPUDATE, g.FECHAUPDAT, g.USUARIO, g.SEMANA,
g.DTOTALHOMBRES, g.DTOTALMUJERES,
e.NOMBREOFICIAL AS establecimiento,
ov.DESCRIPCION AS Institucion,
ov3.DESCRIPCION AS TIPO_INSTITUCION,
s.SEMANA AS semana_des,
p.DESCRIPCION  AS Parroquia_des,
c.DESCRIPCION  AS Canton_des,
p2.DESCRIPCION AS Provincia_des,
c2.CODIGO AS Circuito,
d.CODIGO  AS DISTRITO,
z.DESCRIPCION AS ZONA,
c3.CODIGO AS IDE_NOM, c3.NOMBRE AS IDE_COD_NO_SE_PUEDE_ENLAZAR
FROM HCUE_VIGILANCIA.epigrupal_detalle g
LEFT OUTER JOIN HCUE_VIGILANCIA.EPIGRUPAL_CABECERA ec ON ec.ID = g.IDM 
LEFT OUTER JOIN HCUE_SISTEMA.ENTIDAD e ON g.estable = e.ID
LEFT  OUTER JOIN HCUE_CATALOGOS.ORGANICO ov ON ov.ID = e.ORGANICO_ID 
LEFT OUTER  JOIN HCUE_CATALOGOS.ORGANICO ov2 ON ov2.id = ov.ORGANICO_ID 
LEFT OUTER JOIN  HCUE_CATALOGOS.ORGANICO ov3 ON ov3.ID =ov2.ORGANICO_ID
LEFT OUTER JOIN HCUE_CATALOGOS.PARROQUIA p  ON p.ID = e.PARROQUIA_ID 
LEFT OUTER  JOIN HCUE_CATALOGOS.CANTON c ON p.CANTON_ID = c.ID 
LEFT OUTER  JOIN HCUE_CATALOGOS.PROVINCIA p2 ON c.PROVINCIA_ID = p2.ID 
LEFT OUTER  JOIN HCUE_CATALOGOS.CIRCUITO c2 ON c2.ID = e.CIRCUITO_ID 
LEFT OUTER  JOIN HCUE_CATALOGOS.DISTRITO d ON d.ID = c2.DISTRITO_ID 
LEFT OUTER JOIN  HCUE_CATALOGOS.ZONA z ON z.ID = d.ZONA_ID 
LEFT OUTER JOIN HCUE_VIGILANCIA.SEMANAEPI s ON s.ID = g.SEMANA  
LEFT OUTER JOIN HCUE_CATALOGOS.CIE c3 ON g.IDE = c3.ID;


SELECT COUNT(*)
FROM HCUE_VIGILANCIA.epigrupal_detalle g
LEFT OUTER JOIN HCUE_VIGILANCIA.EPIGRUPAL_CABECERA ec ON ec.ID = g.IDM 
LEFT OUTER JOIN HCUE_SISTEMA.ENTIDAD e ON g.estable = e.ID
LEFT  OUTER JOIN HCUE_CATALOGOS.ORGANICO ov ON ov.ID = e.ORGANICO_ID 
LEFT OUTER  JOIN HCUE_CATALOGOS.ORGANICO ov2 ON ov2.id = ov.ORGANICO_ID 
LEFT OUTER JOIN  HCUE_CATALOGOS.ORGANICO ov3 ON ov3.ID =ov2.ORGANICO_ID
LEFT OUTER JOIN HCUE_CATALOGOS.PARROQUIA p  ON p.ID = e.PARROQUIA_ID 
LEFT OUTER  JOIN HCUE_CATALOGOS.CANTON c ON p.CANTON_ID = c.ID 
LEFT OUTER  JOIN HCUE_CATALOGOS.PROVINCIA p2 ON c.PROVINCIA_ID = p2.ID 
LEFT OUTER  JOIN HCUE_CATALOGOS.CIRCUITO c2 ON c2.ID = e.CIRCUITO_ID 
LEFT OUTER  JOIN HCUE_CATALOGOS.DISTRITO d ON d.ID = c2.DISTRITO_ID 
LEFT OUTER JOIN  HCUE_CATALOGOS.ZONA z ON z.ID = d.ZONA_ID 
LEFT OUTER JOIN HCUE_VIGILANCIA.SEMANAEPI s ON s.ID = g.SEMANA  
LEFT OUTER JOIN HCUE_CATALOGOS.CIE c3 ON g.IDE = c3.ID;

SELECT COUNT(*)
FROM HCUE_VIGILANCIA.epigrupal_detalle g;



/* Clasificacion final, sexo y  condicion final estan en la tabla detalle catalogo*/
SELECT * 
    FROM HCUE_CATALOGOS.DETALLECATALOGO c
    WHERE c.DESCRIPCION  LIKE 'RESULTADOMUESTRA';
   
SELECT * 
    FROM HCUE_SISTEMA.PERSONA p  
    WHERE p.NUMEROIDENTIFICACION  LIKE '0401546205';
   
SELECT * 
    FROM HCUE_CATALOGOS.DETALLECATALOGO c
    WHERE c.ID = 1168;
 
SELECT d.ID ,d.DESCRIPCION,c.DESCRIPCION AS Catalogo, c.ID  FROM HCUE_CATALOGOS.DETALLECATALOGO  d
INNER JOIN HCUE_CATALOGOS.CATALOGO c ON c.ID = d.CATALOGO_ID
WHERE d.CATALOGO_ID  IN ( 279);

